/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crops': typeof CropsRoute
  '/dataset': typeof DatasetRoute
  '/explain': typeof ExplainRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/predict': typeof PredictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crops': typeof CropsRoute
  '/dataset': typeof DatasetRoute
  '/explain': typeof ExplainRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/predict': typeof PredictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crops': typeof CropsRoute
  '/dataset': typeof DatasetRoute
  '/explain': typeof ExplainRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/predict': typeof PredictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/crops'
    | '/dataset'
    | '/explain'
    | '/paper'
    | '/performance'
    | '/predict'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/crops'
    | '/dataset'
    | '/explain'
    | '/paper'
    | '/performance'
    | '/predict'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/crops'
    | '/dataset'
    | '/explain'
    | '/paper'
    | '/performance'
    | '/predict'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CropsRoute: typeof CropsRoute
  DatasetRoute: typeof DatasetRoute
  ExplainRoute: typeof ExplainRoute
  PaperRoute: typeof PaperRoute
  PerformanceRoute: typeof PerformanceRoute
  PredictRoute: typeof PredictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CropsRoute: CropsRoute,
  DatasetRoute: DatasetRoute,
  ExplainRoute: ExplainRoute,
  PaperRoute: PaperRoute,
  PerformanceRoute: PerformanceRoute,
  PredictRoute: PredictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
